site:
  title: Rancher documentation
  url: /
  start_page: main@rp-antora::rancher-manager.adoc

content:
    sources:
    # url: ./
    - url: https://github.com/LucasSaintarbor/rancher-ad
      branches: [main]
    - url: https://github.com/jhkrug/kw-ad
      branches: [main]
    - url: https://github.com/LucasSaintarbor/rke2-ad
      branches: [main]
asciidoc:
  extensions:
  - '@asciidoctor/tabs'
ui:

  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true