site:
  title: Rancher documentation
  url: /
  start_page: main@rancher-ad::rancher-manager.adoc

content:
    sources:
    # url: ./
    - url: https://github.com/LucasSaintarbor/rancher-ad
      branches: [main]
    - url: https://github.com/jhkrug/kw-ad
      branches: [main]
    - url: https://github.com/LucasSaintarbor/rke2-ad
      branches: [main]

ui:
  bundle:
    url: https://github.com/uyuni-project/uyuni-docs/blob/master/branding/default-ui/suma/ui-bundle.zip?raw=true
    #url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./susecom-2023

asciidoc:
  extensions:
  - '@asciidoctor/tabs'