= Generate and View Traffic from Istio

This section describes how to view the traffic that is being managed by Istio.

== The Kiali Traffic Graph

The Istio overview page provides a link to the Kiali dashboard. From the Kiali dashboard, you are able to view graphs for each namespace. The Kiali graph provides a powerful way to visualize the topology of your Istio service mesh. It shows you which services communicate with each other.
[NOTE]
.Prerequisites:
====

To enable traffic to show up in the graph, ensure you have prometheus installed in the cluster. Rancher-istio installs Kiali configured by default to work with the rancher-monitoring chart. You can use rancher-monitoring or install your own monitoring solution. Optional: you can change configuration on how data scraping occurs by setting the xref:../../../integrations-in-rancher/istio/configuration-options/selectors-and-scrape-configurations.adoc[Selectors & Scrape Configs] options.
====


To see the traffic graph,

. In the cluster where Istio is installed, click *Istio* in the left navigation bar.
. Click the *Kiali* link.
. Click on *Graph* in the side nav.
. Change the namespace in the *Namespace* dropdown to view the traffic for each namespace.

If you refresh the URL to the BookInfo app several times, you should be able to see green arrows on the Kiali graph showing traffic to `v1` and `v3` of the `reviews` service. The control panel on the right side of the graph lets you configure details including how many minutes of the most recent traffic should be shown on the graph.

For additional tools and visualizations, you can go to Grafana, and Prometheus dashboards from the *Monitoring* *Overview* page
